<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Entities\Entities.csproj" />
      <ProjectReference Include="..\Features.Debugging\Features.Debugging.csproj" />
      <ProjectReference Include="..\Systems\Systems.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LightInject" Version="7.0.1" />
    </ItemGroup>

</Project>
