//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameDesktop.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameDesktop.Resources.Configs", typeof(Configs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Fighting/down.json.
        /// </summary>
        internal static string PlayerFightingDown {
            get {
                return ResourceManager.GetString("PlayerFightingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Fighting/left.json.
        /// </summary>
        internal static string PlayerFightingLeft {
            get {
                return ResourceManager.GetString("PlayerFightingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Fighting/right.json.
        /// </summary>
        internal static string PlayerFightingRight {
            get {
                return ResourceManager.GetString("PlayerFightingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Fighting/up.json.
        /// </summary>
        internal static string PlayerFightingUp {
            get {
                return ResourceManager.GetString("PlayerFightingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/LayingDown/left.json.
        /// </summary>
        internal static string PlayerLayingDownLeft {
            get {
                return ResourceManager.GetString("PlayerLayingDownLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/LayingDown/right.json.
        /// </summary>
        internal static string PlayerLayingDownRight {
            get {
                return ResourceManager.GetString("PlayerLayingDownRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Running/down.json.
        /// </summary>
        internal static string PlayerRunningDown {
            get {
                return ResourceManager.GetString("PlayerRunningDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Running/left.json.
        /// </summary>
        internal static string PlayerRunningLeft {
            get {
                return ResourceManager.GetString("PlayerRunningLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Running/right.json.
        /// </summary>
        internal static string PlayerRunningRight {
            get {
                return ResourceManager.GetString("PlayerRunningRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Running/up.json.
        /// </summary>
        internal static string PlayerRunningUp {
            get {
                return ResourceManager.GetString("PlayerRunningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Standing/down.json.
        /// </summary>
        internal static string PlayerStandingDown {
            get {
                return ResourceManager.GetString("PlayerStandingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Standing/left.json.
        /// </summary>
        internal static string PlayerStandingLeft {
            get {
                return ResourceManager.GetString("PlayerStandingLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Standing/right.json.
        /// </summary>
        internal static string PlayerStandingRight {
            get {
                return ResourceManager.GetString("PlayerStandingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/Configs/SpriteSheets/Player/Standing/up.json.
        /// </summary>
        internal static string PlayerStandingUp {
            get {
                return ResourceManager.GetString("PlayerStandingUp", resourceCulture);
            }
        }
    }
}
