<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Components\Components.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="LDtkMonogame" Version="1.3.2" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="LightInject">
        <HintPath>..\..\..\..\..\.nuget\packages\lightinject\6.6.4\lib\net6.0\LightInject.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
