<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LightInject" Version="6.6.4"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constants\Constants.csproj" />
    <ProjectReference Include="..\Systems.Debugging\Systems.Debugging.csproj" />
    <ProjectReference Include="..\Systems\Systems.csproj" />
    <ProjectReference Include="..\UI\UI.csproj" />
  </ItemGroup>

</Project>
