<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Serilog" Version="3.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Components\Components.csproj" />
      <ProjectReference Include="..\Entities\Entities.csproj" />
      <ProjectReference Include="..\External\MonoGame.ImGuiNet\MonoGame.ImGuiNet\Monogame.ImGuiNet.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="LightInject">
        <HintPath>..\..\..\..\..\.nuget\packages\lightinject\6.6.4\lib\net6.0\LightInject.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
