<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LDtkMonogame" Version="1.3.2" />
    <PackageReference Include="MonoGame.Aseprite" Version="5.1.1" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Constants\Constants.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Implementations\" />
  </ItemGroup>
</Project>
